[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Set these in Netlify > Site settings > Environment variables

# SPA fallback to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
